# docker-compose.yml
# Use postgres/example user/password credentials
version: '3.1'
services:
  api:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    links:
      - db:db
    depends_on:
      - db
    environment:
      PGRST_DB_URI: postgres://root:password@db:5432/app_db
      PGRST_DB_SCHEMA: api
      PGRST_DB_ANON_ROLE: web_anon

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    restart: always


  swaggergui:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    links:
      - api:api
    environment:
      API_URL: http://localhost:3000