# docker-compose.yml
# Use postgres/example user/password credentials
version: '3.1'
services:
  server:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    links:
      - db:db
    environment:
      PGRST_DB_URI: postgres://app_user:password@db:5432/app_db
      PGRST_DB_SCHEMA: api
      PGRST_DB_ANON_ROLE: anon_user

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: password
    volumes:
          - ./:/myscript

  swaggergui:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    links:
      - server:server
    environment:
      API_URL: http://localhost:3000